import Head from "next/head";
import Image from "next/image";
import Iterator from "../components/iterator";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Turing's ReactJS live coding interview
        </h1>

        <h2>Question:</h2>

        <p>
          1 - Create a custom React hook to fetch users from an API
          (https://randomuser.me/api/) and display their picture name on the
          page one.
        </p>
        <p>
          2 - It must return the list of users, the current user, a function to
          fetch the next user and a function to move back to the previous user.
        </p>
        <p>3 - Test the custom React hook in index.tsx</p>
        <Iterator />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}